<a href="https://colab.research.google.com/github/yudhiesh1997/Tensorflow-Tutorial/blob/master/Tutorial1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf

TensorFlow 2.x selected.


In [3]:
# Load and prepare the MNIST dataset

mnist = tf.keras.datasets.mnist

(x_train, y_train) , (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0 , x_test / 255.0


11493376/11490434 [==============================] - 0s 0us/step


In [0]:
# Build the Sequential model 
# Select an optimizer
# Loss functionn for training 

model = tf.keras.Sequential([
  tf.keras.layers.Flatten(input_shape=(28,28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[-1.570886  , -0.51255953,  0.57483333,  0.61522436, -0.24176241,
         0.4056592 , -0.01830032,  0.06059   ,  0.0077965 ,  0.35923162]],
      dtype=float32)

In [7]:
# softmax converts logits to probabilities
tf.nn.softmax(predictions).numpy()

array([[0.01855297, 0.05346122, 0.1585943 , 0.16513121, 0.07008814,
        0.13391098, 0.08763809, 0.09483192, 0.08995527, 0.12783593]],
      dtype=float32)

In [0]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
# Sparse Categorical Crossentropy returns a scalar loss for each example
loss_fn(y_train[:1], predictions).numpy()
# This loss is equal to the -log probability of the true class
# -tf.log(1/10 -= 2.3

2.01058

In [0]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [12]:
model.fit(x_train, y_train, epochs = 5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 5s 84us/sample - loss: 0.2890 - accuracy: 0.9162
Epoch 2/5
60000/60000 [==============================] - 5s 76us/sample - loss: 0.1369 - accuracy: 0.9601
Epoch 3/5
60000/60000 [==============================] - 4s 73us/sample - loss: 0.1026 - accuracy: 0.9689
Epoch 4/5
60000/60000 [==============================] - 4s 73us/sample - loss: 0.0857 - accuracy: 0.9736
Epoch 5/5
60000/60000 [==============================] - 4s 72us/sample - loss: 0.0720 - accuracy: 0.9776


In [13]:
model.evaluate(x_test, y_test, verbose =1)
# verbose = 1 is progress bar

10000/10000 [==============================] - 0s 44us/sample - loss: 0.0747 - accuracy: 0.9773


[0.07465614166997839, 0.9773]

In [14]:
# To return a probability model
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.7857913e-07, 6.3910449e-10, 1.9522545e-06, 3.3318240e-05,
        8.0157651e-11, 3.1839451e-07, 2.3931440e-13, 9.9989188e-01,
        6.1248073e-07, 7.1631388e-05],
       [2.3008367e-08, 4.1488613e-05, 9.9994481e-01, 5.6394083e-06,
        1.0339796e-15, 8.0434565e-06, 3.8798508e-08, 2.4433146e-13,
        3.4147146e-08, 2.3395435e-13],
       [3.2059909e-06, 9.9941504e-01, 4.3572647e-05, 2.2662337e-06,
        3.7833724e-05, 1.8511179e-06, 4.7581056e-05, 3.8168952e-04,
        6.6472487e-05, 3.0910951e-07],
       [9.9999583e-01, 4.2588991e-11, 1.0466322e-06, 3.6515215e-09,
        1.4934033e-08, 7.7986797e-08, 9.0102623e-07, 3.8405325e-08,
        4.8032939e-10, 2.1198050e-06],
       [2.8994773e-06, 2.6117926e-09, 1.4440280e-06, 3.4169563e-08,
        9.9810994e-01, 1.0476642e-06, 1.0339922e-06, 4.0282695e-05,
        9.2676208e-07, 1.8423672e-03]], dtype=float32)>